receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  elasticsearch:
    endpoint: http://elasticsearch:9200
    logs_index: "my-logs-test"
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:9090
  otlp/yaeger:
    endpoint: "yaeger:4317"
    tls:
      insecure: true


service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [elasticsearch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp/yaeger]

  # configure internal telemetry of the collector
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 9091