name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-action@v1
        with:
          sonar-project-key: 'StudentReportLLM'
          sonar-project-name: 'StudentReportLLM'
          sonar-host-url: 'https://sonarcloud.io'
          sonar-login: ${{ secrets.SONAR_TOKEN }}

      - name: Build and Tag Docker Images
        run: |
          docker build -t llmproject/studentreportllm:latest -f services/conversion/Dockerfile .
          docker tag llmproject/studentreportllm:latest ${{ secrets.DOCKER_HUB_USERNAME }}/studentreportllm:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/studentreportllm:latest
