name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker images using Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Start services with Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: docker-compose -f docker-compose.yml run app python -m unittest discover -s tests

      - name: Shutdown services
        run: docker-compose -f docker-compose.yml down

      - name: Push Docker images to Docker Hub
        run: |
          docker tag llmproject/studentreportllm:latest ${{ secrets.DOCKER_HUB_USERNAME }}/studentreportllm:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/studentreportllm:latest
